# Generated by Django 5.0.4 on 2024-04-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Db',
            new_name='Bb',
        ),
    ]
